
---

- name: Install Nginx Web Server and Upload WebPage
  hosts: slave2
  any_errors_fatal: true
  become: true

  roles:
#    - deploy_web_nginx
    - { role: nginx_up, ansible_system == Linux }
    - content_delivery

...

